environments:
    - name: dev
      configs:
          endpoints:
              production:
                  url: 'https://dev.wso2.com'
              sandbox:
                  url: 'https://dev.sandbox.wso2.com'
    - name: test
      configs:
          endpoints:
              production:
                  url: 'https://test.wso2.com'
              sandbox:
                  url: 'https://test.sandbox.wso2.com'
